### ISSUE TITLE
[Feature] Add --exclude to octo pack

### ISSUE THREAD

**Issue by ulrichb** [OctopusDeploy/OctopusCLI#106]
`octo pack` already has a `--include` parameter (supporting globs).

In addition, please add an `--exclude` parameter.

Use cases:
* Exclude **/*.config files
* Exclude **/*.local.env files
* Exclude AppData/** dir

**Comment by benPearce1** [comment]
The Octopus CLI is being deprecated and has been replaced by https://github.com/OctopusDeploy/cli.
The feature request has been moved to the CLI repository https://github.com/OctopusDeploy/cli/issues/214
