### ISSUE TITLE
Unable to find package with version 3451.0.3458

### ISSUE THREAD

**Issue by mboltuc** [OctopusDeploy/OctopusCLI#162]
Today we started getting this error when restoring dotnet tools:
```
Unable to find package octopus.dotnet.cli with version (= 3451.0.3458)
```
It looks like the latest version of the tools is now 7.4.3658.  Any insight on what happened?

**Comment by slewis74** [comment]
The packages with Id `3451.0.3458` were the result of an erroneous build and deployment that occurred a few months ago (the code was right in that build, applying the version number just did the wrong thing). We had not realised that it was still being listed in some places until this week. We also discovered that [unlisting it didn't have quite the result we'd hoped for in some scenarios](https://github.com/dotnet/sdk/issues/24037).
We put in a support ticket with NuGet and had it deleted. `7.4.3659` is the correct current latest version. Apologies for the confusion this caused.
