### ISSUE TITLE
Additional support for listing and deleting of Runbook Runs

### ISSUE THREAD

**Issue by mraming** [OctopusDeploy/OctopusCLI#244]
Enhance the Octopus CLI to support the List-Runbooks, List-RunbookRuns, and Delete-RunbookRuns commands.

The rationale for this is that I'd like to automate some of the maintenance aspects of these, like cleaning up RunBook Runs after a while.

One scenario where I need this is because I'm unable to delete a project which has a fairly large number of runbook runs. Likely some timeout issue (I've not investigated). Deleting the runbook runs from the project before deleting the project worked around that issue.

**Comment by benPearce1** [comment]
Hi @mraming,

We are no longer doing feature work in OctopusCLI as it has been superseded by https://github.com/OctopusDeploy/cli.  
There is an [open issue](https://github.com/OctopusDeploy/cli/issues/165) that would support this request, please add any further comments (or PRs) to that one.
