### ISSUE TITLE
netcoreapp3.1 upgrade on minor version

### ISSUE THREAD

**Issue by lngr** [OctopusDeploy/OctopusCLI#35]
The latest commit updated the runtime from 2.1 to 3.1:

https://github.com/OctopusDeploy/OctopusCLI/commit/fb0528148c0c68e9e430ababaf133486dbd279e6

This breaks support on environments, where 3.1 is not yet supported/available.

Unfortunately, this was released in a minor version bump (6.17.0 => 6.17.2). (Not sure if you are following the semantic versioning pattern).

**Comment by matt-richardson** [comment]
We are now publishing as self-contained executables (as in the runtime is baked in), so this _shouldn't_ be an issue...
Please do let us know if that is not the case.

**Comment by lngr** [comment]
This is from our MyGet buildserver:

Commandline:

    dotnet tool install Octopus.DotNet.Cli --tool-path tools

<img width="470" alt="Anmerkung 2020-01-30 100130" src="https://user-images.githubusercontent.com/1508058/73434696-84ebb400-4347-11ea-8ce1-d8f4badad28b.png">

MyGet does not yet support 3.x.

I'm now fixing the version and it works:

    dotnet tool install Octopus.DotNet.Cli --tool-path tools --version 6.17.0

**Comment by matt-richardson** [comment]
Whoops - sorry about that.

We'll pull that release and get our ducks in order a bit better before we re-release.

**Comment by thedewi** [comment]
6.17.3 has been shipped which restores how things worked in 6.17.0.
