### ISSUE TITLE
Azure DevOps Octopus Steps Cannot Locate Octo Tool

### ISSUE THREAD

**Issue by ndunn990** [OctopusDeploy/OctopusCLI#40]
I have a very simple Azure DevOps Pipeline that runs on an agent on a local on-prem machine of ours.

So, context:

- Build Server (on-prem) running Ubuntu 16.04
- Azure DevOps Octopus Steps using the embedded version of the Octo Tool (default behavior), which is 6.17.4 at the moment.

**Issue:** Pipeline then fails on the first Octo 'pack' step.

![screenshot_2020-02-13_12-49-05_527426206](https://user-images.githubusercontent.com/20825134/74463089-41249e80-4e5f-11ea-8854-d9efa358401a.png)

We allow the steps to use the embedded version of the Octo tool (the default behavior, I believe). However, after supposedly finding the tool, it fails to...well, find it, when it attempts to run, as you can see above. However, they _are_ there:

![screenshot_2020-02-13_12-54-55_472269675](https://user-images.githubusercontent.com/20825134/74463619-14bd5200-4e60-11ea-8cba-117258196912.png)

If I try using the 'Use Octo Command Line Tool Version' step, it will find it in the 'tool cache' and move on, but then fail to find it when it attempts to run. I also tried deleting the entire cache directory, but the same issue occurred.

I resolved this issue by capitalizing the following in the tool cache directory (agent/_work/_tool/Octo/6.17.4/x64):

octo -> **O**cto
octo.dll -> **O**cto.dll
octo.runtimeconfig.json -> **O**cto.runtimeconfig.json

**Comment by matt-richardson** [comment]
Hi @ndunn990, sorry to see we've broken this for you.

Glad to see that you figured out a workaround.

We've been nose to the grindstone trying to figure out a resolution & we're about to revert back our recent changes and ship `6.17.6`. 

We've also got some work in progress to make our AzureDevOps extension (OctoTFS) work better with the case change for when we roll forward again.

We'll update when we've got further news.

**Comment by thedewi** [comment]
Hi @ndunn990.

Since the previous message, we've shipped an update to the Azure DevOps extension (currently 4.1.425) that we believe has addressed this problem, so I'm hoping your agent is now fetching Octopus CLI 7.0.0 and invoking it correctly.

If that's not the case, we'd love to look into it further and solve it, so please feel free to reach out again.

Thanks.

**Comment by ndunn990** [comment]
Hi @thedewi.

I just had another pipeline run the Octopus CLI Version 7.10. I deleted the entire 'Octo' tool directory to ensure I was in a clean state. Unfortunately, it failed once more for the same reason.
[9.txt](https://github.com/OctopusDeploy/OctopusCLI/files/4232610/9.txt)

I then implemented the work around I described earlier:  octo to **O**cto, octo.dll to **O**cto.dll, and octo.runtimeconfig.json to **Octo.runtimeconfig.json. Once again, the workaround resolved my issue, but it looks like there still might be problem.

Just in case, I patched our build servers, but I ran into the same issue. Are we the only ones having this problem? I'm not sure what we might be doing that's particularly unique, quite yet.

- Azure DevOps Build Agent (Linux) Version: 2.164.8
- Build Server: Ubuntu 16.04 LTS
- DotNet: 2.2.402

**Comment by matt-richardson** [comment]
Hi @ndunn990 

I’m far from an expert in this extension, but from the logs, it appears you’re running version 3.0.222 of the extension. Can you confirm if that’s the case?

If so, can you try updating to the latest version? The latest version is available at https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks, which is at version 4.1.425.

There’s a chance that the version number is the task version number - not sure... The more I look into it, the more I think that’s the case, actually. 

Best bet is to double check you’ve got the latest extension anyway :)

Let me know how you get along.

**Comment by ndunn990** [comment]
Hi @matt-richardson 

So, I checked my organization's extensions and it looks like I've been up-to-date since February 14th.

![screenshot_2020-02-21_11-26-10_261044465](https://user-images.githubusercontent.com/20825134/75052148-19f05180-549d-11ea-85e0-96ced75e41b2.png)

However, that lead me to take another look at my steps within my pipeline. I thought I'd updated all of them, but it looks like one of my 'pack' steps were using version 3. I updated it to version 4, removed the Octo tool directory on the server to ensure a clean state, and successfully ran our pipeline without issue.

So, I'm not sure if the issue _was_ resolved, but I had to update my 'pack' build step, but that does seem to have resolved the issue. Thank you for at least inspiring me to double-check a few things!

Please feel free to close this issue.

**Comment by matt-richardson** [comment]
Thanks for letting us know - sorry for the hassle we caused.
