### ISSUE TITLE
`install-autocomplete` and `complete` commands dont support `--help`

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/OctopusCLI#63]
### `install-autocomplete`

```
PS > .\octo.exe --install-autocomplete --help
Please specify the type of shell to install auto-completion for: --shell=XYZ. Valid values are Pwsh, Zsh, Bash and Powershell.
Exit code: -1
```

### `complete`

```
PS > .\octo.exe complete --help
--help
--helpOutputFormat
```

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Customer wants a Docker image that they can use as a host to run Octopus CLI commands](https://trello.com/c/QshRMaZa/3305-customer-wants-a-docker-image-that-they-can-use-as-a-host-to-run-octopus-cli-commands)
