### ISSUE TITLE
Create Release Argument releaseNotesFile changed to releaseNoteFile

### ISSUE THREAD

**Issue by acavalheiro** [OctopusDeploy/OctopusCLI#70]
Hi,

With the release of version 4.3.3, the argument on create-release changed from releaseNotesFile to releaseNoteFile, missing a s near Notes word, is that intended ?

Thanks

**Comment by emi662002** [comment]
We see our pipeline failing as mentioned above:
7.3.3 Unrecognized command arguments: --releaseNotesFile=D:\agent\_work
7.3.2 works just fine

**Comment by matt-richardson** [comment]
Ahh, apologies for that - It was accidentally introduced in https://github.com/OctopusDeploy/OctopusCLI/commit/ed1b1d81bf35097b626fb8b114a95e99d1f8a70d. I'll have a fix out soon.

In the meantime, you can use `releaseNoteFile` - I'll make it an alias so both will work.

**Comment by acavalheiro** [comment]
Thank you!

**Comment by matt-richardson** [comment]
Just released 7.3.4 that allows both `releaseNotesFile` and `releaseNoteFile` Apologies once again!
