### ISSUE TITLE
Unable to start Octopus CLI (intermittent)

### ISSUE THREAD

**Issue by flin-8** [OctopusDeploy/OctopusCLI#73]
# The bug

Sometimes Octopus CLI may fail to start with a message that looks like:
```
The application to execute does not exist: '/private/var/folders/hj/202p2m5n7r91bbg91h69rl480000gq/T/.net/octo/40kc2l11.14r/octo.dll'.
```
or
```
Error:
  An assembly specified in the application dependencies manifest (octo.deps.json) was not found:
    package: 'Markdig', version: '0.10.4'
    path: 'lib/netstandard1.1/Markdig.dll'
```

This is a [dotnet core issue](https://github.com/dotnet/runtime/issues/3778) that affects all single-file executables. When running the executable, the contents are extracted to a temporary directory and executes from there. The unfortunate thing is that temporary files sometimes get cleaned up by scheduled tasks and other processes, which breaks things. Microsoft has recently [fixed ](https://github.com/dotnet/core-setup/pull/9013) this issue so we will be able to fix this permanently once they releases the new version of NetCore 3.1.

## What I expected to happen

Octopus CLI should work even when some of the files have been cleaned up.

## Affected versions

**Reproduced in 7.3.2**

## Workarounds

The [.net documentation here](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design_3_0.md#extraction-location)​ explains how the extraction location is determined. You can override this in the meantime by setting the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable to somewhere else.

## Links

https://secure.helpscout.net/conversation/1118339129/59694?folderId=2118197
https://help.octopus.com/t/octopus-cli-issues-on-macos/25041

**Comment by matt-richardson** [comment]
Build agents are now using netcore 3.1.4

**Comment by matt-richardson** [comment]
Release note: Fixed intermittent startup issue due to extracted files missing
