### ISSUE TITLE
octopus cli docker image use in CI

### ISSUE THREAD

**Issue by KunalSaini** [OctopusDeploy/OctopusCLI#76]
Hi , I am trying to use `octopusdeploy/octo` docker image in my Jenkins build stage.
I realized the image couldn't be used as its not providing the right entrypoint options according to [this guidline](https://github.com/docker-library/official-images#consistency).

I even tried overriding the entrypoint as below , however couldn't get it running 
```
stage('octopus') {
     agent {
         docker {
               image 'octopusdeploy/octo'
               args '--entrypoint "/bin/sh"'
         }
     }
steps { ... }
```
jenkins tries to run it as following and fails 
```
$ docker run -t -d -u 1000:1000 --entrypoint /bin/sh -w /home/devbuild/workspace/g4-metasys-server_audit_PR-278 -v /home/devbuild/workspace/WPR-278:/home/devbuild/workspace/WPR-278:rw,z -v /home/devbuild/workspace/WPR-278@tmp:/home/devbuild/workspace/WPR-278@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** octopusdeploy/octo cat
```
can the octopus cli image be fixed to follow [docker guidline](https://github.com/docker-library/official-images#consistency)

**Comment by Waldo000000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Customer wants a Docker image that they can use as a host to run Octopus CLI commands](https://trello.com/c/QshRMaZa/3305-customer-wants-a-docker-image-that-they-can-use-as-a-host-to-run-octopus-cli-commands)

**Comment by mcasperson** [comment]
Hi @KunalSaini, 

This is good feedback, and the functionality from the Docker guidelines does make sense. 

Unfortunately at this point we do not have capacity to assign an engineer to this issue, and this feature is unlikely to be implemented in the short term. The only workaround I can suggest is to fork the Dockerfile and implement the ENTRYPOINT to get the required functionality. 

I apologize for the inconvenience, and we do appreciate you taking the time to report the issue.

Regards
Matt

**Comment by KunalSaini** [comment]
In case anyone else find them-self in this situation, following is the Jenkin file docker definition that worked for me as a workaround.
```
stage('octopus') {
	options { skipDefaultCheckout() }
            agent {
                docker {
                    image 'octopusdeploy/octo'
                    args '--entrypoint='
                }
            }
```
